---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "user"
            - name: MYSQL_DATABASE
              value: "messagerie"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: init-sql
          configMap:
            name: mysql-init-sql
            items:
              - key: init.sql
                path: init.sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
        - name: postfix
          image: postfix 
          ports:
            - containerPort: 25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      containers:
        - name: dovecot
          image: dovecot
          ports:
            - containerPort: 143
            - containerPort: 110
          volumeMounts:
            - name: dovecot-storage
              mountPath: /home/vmail
      volumes:
        - name: dovecot-storage
          persistentVolumeClaim:
            claimName: dovecot-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - name: roundcube
          image: roundcube/roundcubemail
          ports:
            - containerPort: 80
          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: dovecot
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "143"
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: postfix
            - name: ROUNDCUBEMAIL_SMTP_PORT
              value: "25"
            - name: ROUNDCUBEMAIL_DB_TYPE
              value: mysql
            - name: ROUNDCUBEMAIL_DB_HOST
              value: mysql
            - name: ROUNDCUBEMAIL_DB_PORT
              value: "3306"
            - name: ROUNDCUBEMAIL_DB_USER
              value: user
            - name: ROUNDCUBEMAIL_DB_PASSWORD
              value: user
            - name: ROUNDCUBEMAIL_DB_NAME
              value: messagerie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_ARBITRARY
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: admin
          ports:
            - containerPort: 80
