---
apiVersion: v1
kind: Pod
metadata:
  name: mailstack-pod
spec:
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
    - name: dovecot-persistent-storage
      persistentVolumeClaim:
        claimName: dovecot-pvc
    - name: mysql-init-volume
      configMap:
        name: mysql-init-sql
  containers:
    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: user
        - name: MYSQL_DATABASE
          value: messagerie
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
        - mountPath: /docker-entrypoint-initdb.d/
          name: mysql-init-volume
      ports:
        - containerPort: 3306

    - name: postfix
      image: postfix
      ports:
        - containerPort: 25

    - name: dovecot
      image: dovecot
      volumeMounts:
        - mountPath: /home/vmail
          name: dovecot-persistent-storage
      ports:
        - containerPort: 143
        - containerPort: 110

    - name: roundcube
      image: roundcube/roundcubemail
      env:
        - name: ROUNDCUBEMAIL_DEFAULT_HOST
          value: dovecot
        - name: ROUNDCUBEMAIL_DEFAULT_PORT
          value: "143"
        - name: ROUNDCUBEMAIL_SMTP_SERVER
          value: postfix
        - name: ROUNDCUBEMAIL_SMTP_PORT
          value: "25"
        - name: ROUNDCUBEMAIL_DB_TYPE
          value: mysql
        - name: ROUNDCUBEMAIL_DB_HOST
          value: localhost
        - name: ROUNDCUBEMAIL_DB_PORT
          value: "3306"
        - name: ROUNDCUBEMAIL_DB_USER
          value: user
        - name: ROUNDCUBEMAIL_DB_PASSWORD
          value: user
        - name: ROUNDCUBEMAIL_DB_NAME
          value: messagerie
      ports:
        - containerPort: 80

    - name: phpmyadmin
      image: phpmyadmin
      env:
        - name: PMA_ARBITRARY
          value: "1"
      ports:
        - containerPort: 80

    - name: admin
      image: admin
      ports:
        - containerPort: 80
---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ConfigMap for init.sql
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  labels:
    app: mysql
data:
  init.sql:
   ../init.sql
    CREATE TABLE IF NOT EXISTS test (id INT);
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: postfix
spec:
  selector:
    app: postfix
  ports:
    - port: 25
      targetPort: 25
---
apiVersion: v1
kind: Service
metadata:
  name: dovecot
spec:
  selector:
    app: dovecot
  ports:
    - name: imap
      port: 14300
      targetPort: 143
    - name: pop3
      port: 11000
      targetPort: 110

---
apiVersion: v1
kind: Service
metadata:
  name: roundcube
spec:
  selector:
    app: roundcube
  ports:
    - port: 8003
      targetPort: 80
      nodePort: 30083
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 8000
      targetPort: 80
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  selector:
    app: admin
  ports:
    - port: 8004
      targetPort: 80
      nodePort: 30004
  type: NodePort
