---
- name: deployment on the local system
  hosts: mailserver
  become: yes
  tasks:

    - name: Mettre updating packets
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installing the required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Adding docker GPG apt_key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: adding docker 
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: install docker compose
      pip:
        name: docker-compose
        executable: pip3

    - name: check up that docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Starting the containers with docker compose
      command: docker compose up -d
      args:
        chdir: /home/chrisorg/Labs/Project/docker

