---
- name: Deployment of the mail infrastructure on the remote system
  hosts: mailserver
  become: yes
  tasks:
  
    - name: Update package lists and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install docker-compose via pip3
      pip:
        name: docker-compose
        executable: pip3

    - name: Ensure Docker is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start containers with Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/chrisorg/Labs/Project/docker
